##
## EPITECH PROJECT, 2023
## Unit tests
## File description:
## The Makefile of the unit tests
##

NAME		=	unit_tests


SRCS		+=	../lib/my/my_printf/find_format.c
SRCS		+=	../lib/my/my_printf/flag_c.c
SRCS		+=	../lib/my/my_printf/flag_s.c
SRCS		+=	../lib/my/my_printf/flag_d.c
SRCS		+=	../lib/my/my_printf/flag_i.c
SRCS		+=	../lib/my/my_printf/flag_p.c
SRCS		+=	../lib/my/my_printf/flag_o.c
SRCS		+=	../lib/my/my_printf/flag_u.c
SRCS		+=	../lib/my/my_printf/flag_x.c
SRCS		+=	../lib/my/my_printf/flag_bigx.c
SRCS		+=	../lib/my/my_printf/flag_e.c
SRCS		+=	../lib/my/my_printf/flag_bige.c
SRCS		+=	../lib/my/my_printf/flag_f.c
SRCS		+=	../lib/my/my_printf/flag_bigf.c
SRCS		+=	../lib/my/my_printf/flag_g.c
SRCS		+=	../lib/my/my_printf/flag_bigg.c
SRCS		+=	../lib/my/my_printf/flag_a.c
SRCS		+=	../lib/my/my_printf/flag_biga.c
SRCS		+=	../lib/my/my_printf/flag_n.c
SRCS		+=	../lib/my/my_printf/flag_b.c
SRCS		+=	../lib/my/my_printf/flag_bigs.c
SRCS		+=	../lib/my/my_printf/flag_bigd.c
SRCS		+=	../lib/my/my_printf/get_format.c
SRCS		+=	../lib/my/my_printf/my_show_formating.c
SRCS		+=	../lib/my/my_printf/sub_format_double.c
SRCS		+=	../lib/my/my_printf/format_it_int.c
SRCS		+=	../lib/my/my_printf/format_it_double.c
SRCS		+=	../lib/my/my_printf/precise_it_int.c
SRCS		+=	../lib/my/my_printf/precise_it_double.c
SRCS		+=	../lib/my/my_printf/round_flag_a.c
SRCS		+=	../lib/my/my_printf/format_it_str.c
SRCS		+=	../lib/my/my_printf/format_it_char.c
SRCS		+=	../lib/my/my_printf/sub_format_int.c
SRCS		+=	../lib/my/my_printf/sub_format_str.c
SRCS		+=	../lib/my/my_printf/sub_format_char.c
SRCS		+=	../lib/my/my_printf/specifier_int.c
SRCS		+=	../lib/my/my_printf/specifier_base.c

SRCS		+=	../lib/my/my_array_len.c
SRCS		+=	../lib/my/my_char_is.c
SRCS		+=	../lib/my/my_char_is_alpha.c
SRCS		+=	../lib/my/my_char_is_num.c
SRCS		+=	../lib/my/my_char_is_printable.c
SRCS		+=	../lib/my/my_compute_factorial_rec.c
SRCS		+=	../lib/my/my_compute_power_rec.c
SRCS		+=	../lib/my/my_compute_power_rec_size_t.c
SRCS		+=	../lib/my/my_compute_square_root.c
SRCS		+=	../lib/my/my_concat_params.c
SRCS		+=	../lib/my/my_convert_base.c
SRCS		+=	../lib/my/my_convert_base_size_t.c
SRCS		+=	../lib/my/my_convert_base_unsigned.c
SRCS		+=	../lib/my/my_count_letter.c
SRCS		+=	../lib/my/my_find_nbr.c
SRCS		+=	../lib/my/my_find_prime_sup.c
SRCS		+=	../lib/my/my_find_prime_inf.c
SRCS		+=	../lib/my/my_fprintf.c
SRCS		+=	../lib/my/my_free_array.c
SRCS		+=	../lib/my/my_free_ptr.c
SRCS		+=	../lib/my/my_getnbr.c
SRCS		+=	../lib/my/my_getnbr_base.c
SRCS		+=	../lib/my/my_getnbr_float.c
SRCS		+=	../lib/my/my_is_prime.c
SRCS		+=	../lib/my/my_isneg.c
SRCS		+=	../lib/my/my_params_to_array.c
SRCS		+=	../lib/my/my_print_combn.c
SRCS		+=	../lib/my/my_print_params.c
SRCS		+=	../lib/my/my_printf.c
SRCS		+=	../lib/my/my_putchar.c
SRCS		+=	../lib/my/my_putnbr.c
SRCS		+=	../lib/my/my_putnbr_base.c
SRCS		+=	../lib/my/my_putstr.c
SRCS		+=	../lib/my/my_putstr_error.c
SRCS		+=	../lib/my/my_putstr_fd.c
SRCS		+=	../lib/my/my_putstr_fd_free.c
SRCS		+=	../lib/my/my_putstr_sized.c
SRCS		+=	../lib/my/my_rev_params.c
SRCS		+=	../lib/my/my_revstr.c
SRCS		+=	../lib/my/my_round_float_str.c
SRCS		+=	../lib/my/my_show_param_array.c
SRCS		+=	../lib/my/my_show_word_array.c
SRCS		+=	../lib/my/my_showmem.c
SRCS		+=	../lib/my/my_showstr.c
SRCS		+=	../lib/my/my_sort_int_array.c
SRCS		+=	../lib/my/my_sort_params.c
SRCS		+=	../lib/my/my_str_contains.c
SRCS		+=	../lib/my/my_str_is.c
SRCS		+=	../lib/my/my_str_isalpha.c
SRCS		+=	../lib/my/my_str_islower.c
SRCS		+=	../lib/my/my_str_isnum.c
SRCS		+=	../lib/my/my_str_isprintable.c
SRCS		+=	../lib/my/my_str_isupper.c
SRCS		+=	../lib/my/my_str_nbr.c
SRCS		+=	../lib/my/my_str_nbr_base_long_long_int.c
SRCS		+=	../lib/my/my_str_nbr_base_unsigned.c
SRCS		+=	../lib/my/my_str_nbr_base_unsigned_long.c
SRCS		+=	../lib/my/my_str_nbr_base_unsigned_short.c
SRCS		+=	../lib/my/my_str_nbr_base_unsigned_short_short.c
SRCS		+=	../lib/my/my_str_nbr_base_unsigned_size_t.c
SRCS		+=	../lib/my/my_str_nbr_long_long.c
SRCS		+=	../lib/my/my_str_nbr_short.c
SRCS		+=	../lib/my/my_str_nbr_short_short.c
SRCS		+=	../lib/my/my_str_nbr_size_t.c
SRCS		+=	../lib/my/my_str_nbr_unsigned.c
SRCS		+=	../lib/my/my_str_nbr_unsigned_long.c
SRCS		+=	../lib/my/my_str_to_word_array.c
SRCS		+=	../lib/my/my_str_to_word_array_select.c
SRCS		+=	../lib/my/my_str_to_word_array_string.c
SRCS		+=	../lib/my/my_strcapitalize.c
SRCS		+=	../lib/my/my_strcat.c
SRCS		+=	../lib/my/my_strcmp.c
SRCS		+=	../lib/my/my_strcpy.c
SRCS		+=	../lib/my/my_strdup.c
SRCS		+=	../lib/my/my_strdup_word_array.c
SRCS		+=	../lib/my/my_strerror.c
SRCS		+=	../lib/my/my_strict_find_nbr.c
SRCS		+=	../lib/my/my_strict_getnbr.c
SRCS		+=	../lib/my/my_strict_getnbr_float.c
SRCS		+=	../lib/my/my_strlen.c
SRCS		+=	../lib/my/my_strlowcase.c
SRCS		+=	../lib/my/my_strncat.c
SRCS		+=	../lib/my/my_strncmp.c
SRCS		+=	../lib/my/my_strncpy.c
SRCS		+=	../lib/my/my_strndup.c
SRCS		+=	../lib/my/my_strstr.c
SRCS		+=	../lib/my/my_strupcase.c
SRCS		+=	../lib/my/my_super_array.c
SRCS		+=	../lib/my/my_super_number.c
SRCS		+=	../lib/my/my_swap.c

SRCS		+=	../lib/mylist/my_concat_list.c
SRCS		+=	../lib/mylist/my_delete_circled_list.c
SRCS		+=	../lib/mylist/my_delete_list.c
SRCS		+=	../lib/mylist/my_delete_nodes.c
SRCS		+=	../lib/mylist/my_find_node.c
SRCS		+=	../lib/mylist/my_list_size.c
SRCS		+=	../lib/mylist/my_list_size_circled.c
SRCS		+=	../lib/mylist/my_list_to_array.c
SRCS		+=	../lib/mylist/my_list_to_array_circled.c
SRCS		+=	../lib/mylist/my_merge_list.c
SRCS		+=	../lib/mylist/my_params_to_list.c
SRCS		+=	../lib/mylist/my_pop_back.c
SRCS		+=	../lib/mylist/my_pop_front.c
SRCS		+=	../lib/mylist/my_pop_node.c
SRCS		+=	../lib/mylist/my_push_back.c
SRCS		+=	../lib/mylist/my_push_back_circled.c
SRCS		+=	../lib/mylist/my_push_front.c
SRCS		+=	../lib/mylist/my_previous_to_next.c
SRCS		+=	../lib/mylist/my_rev_list.c
SRCS		+=	../lib/mylist/my_show_list.c
SRCS		+=	../lib/mylist/my_sort_list.c

SRCS		+=	../lib/mymemory/my_calloc.c
SRCS		+=	../lib/mymemory/my_free.c
SRCS		+=	../lib/mymemory/my_malloc.c
SRCS		+=	../lib/mymemory/my_malloc_strdup.c
SRCS		+=	../lib/mymemory/my_malloc_strdup_word_array.c
SRCS		+=	../lib/mymemory/my_malloc_strndup.c
SRCS		+=	../lib/mymemory/my_memchr.c
SRCS		+=	../lib/mymemory/my_memcmp.c
SRCS		+=	../lib/mymemory/my_memcpy.c
SRCS		+=	../lib/mymemory/my_memmove.c
SRCS		+=	../lib/mymemory/my_memset.c
SRCS		+=	../lib/mymemory/my_realloc.c

SRCS		+=	../src/builtins/about.c
SRCS		+=	../src/builtins/alias.c
SRCS		+=	../src/builtins/cd.c
SRCS		+=	../src/builtins/echo.c
SRCS		+=	../src/builtins/else.c
SRCS		+=	../src/builtins/endif.c
SRCS		+=	../src/builtins/env.c
SRCS		+=	../src/builtins/exec.c
SRCS		+=	../src/builtins/exit.c
SRCS		+=	../src/builtins/foreach.c
SRCS		+=	../src/builtins/help.c
SRCS		+=	../src/builtins/history.c
SRCS		+=	../src/builtins/if.c
SRCS		+=	../src/builtins/repeat.c
SRCS		+=	../src/builtins/set.c
SRCS		+=	../src/builtins/setenv.c
SRCS		+=	../src/builtins/source.c
SRCS		+=	../src/builtins/unalias.c
SRCS		+=	../src/builtins/unset.c
SRCS		+=	../src/builtins/unsetenv.c
SRCS		+=	../src/builtins/where.c
SRCS		+=	../src/builtins/which.c
SRCS		+=	../src/globbing/globbing.c
SRCS		+=	../src/history/history_file.c
SRCS		+=	../src/history/event.c
SRCS		+=	../src/inhibitors/array_separators.c
SRCS		+=	../src/inhibitors/array_string.c
SRCS		+=	../src/inhibitors/inhibitors.c
SRCS		+=	../src/line-editing/ansi.c
SRCS		+=	../src/line-editing/my_getline.c
SRCS		+=	../src/line-editing/termios.c
SRCS		+=	../src/parsing/condition.c
SRCS		+=	../src/parsing/input_command.c
SRCS		+=	../src/parsing/parsing.c
SRCS		+=	../src/parsing/replace_alias.c
SRCS		+=	../src/parsing/replace_variable.c
SRCS		+=	../src/parsing/tilde.c
SRCS		+=	../src/prompt/prompt.c
SRCS		+=	../src/prompt/git_repository.c
SRCS		+=	../src/prompt/title.c
SRCS		+=	../src/separators/backticks.c
SRCS		+=	../src/separators/left_redirections.c
SRCS		+=	../src/separators/multiple_commands.c
SRCS		+=	../src/separators/operators.c
SRCS		+=	../src/separators/parentheses.c
SRCS		+=	../src/separators/pipes.c
SRCS		+=	../src/separators/redirections.c
SRCS		+=	../src/separators/right_redirections.c
SRCS		+=	../src/command.c
SRCS		+=	../src/config_file.c
SRCS		+=	../src/environnement.c
SRCS		+=	../src/scripting.c
SRCS		+=	../src/shell.c
SRCS		+=	../src/signals.c

TESTS		+=	functional_test_alias.c
TESTS		+=	functional_test_backticks.c
TESTS		+=	functional_test_cd.c
TESTS		+=	functional_test_commands.c
TESTS		+=	functional_test_environnement.c
TESTS		+=	functional_test_exit.c
TESTS		+=	functional_test_globbing.c
TESTS		+=	functional_test_inhibitors.c
TESTS		+=	functional_test_operators.c
TESTS		+=	functional_test_other.c
TESTS		+=	functional_test_parsing.c
TESTS		+=	functional_test_pipes.c
TESTS		+=	functional_test_redirections.c
TESTS		+=	functional_test_repeat.c
TESTS		+=	functional_test_variables.c
TESTS		+=	functional_test_where.c
TESTS		+=	functional_test_which.c

TESTS		+=	test_my_lib.c
TESTS		+=	test_my_printf.c
TESTS		+=	test_mycsfml_lib.c
TESTS		+=	test_myhashtable_lib.c
TESTS		+=	test_mylist_lib.c
TESTS		+=	test_mymemory_lib.c
TESTS		+=	test_mysh_old.c

TMPFILE		+=	\"test\ file\"
TMPFILE		+=	.42sh_history
TMPFILE		+=	.42shrc
TMPFILE		+=	.toto
TMPFILE		+=	\ "test|filehere"\  file
TMPFILE		+=	script
TMPFILE		+=	"test&&&file"
TMPFILE		+=	"test 'file'"
TMPFILE		+=	test\ file
TMPFILE		+=	"test;;;file"
TMPFILE		+=	"test<file"
TMPFILE		+=	"test>file"
TMPFILE		+=	test_input.txt
TMPFILE		+=	"test|file"
TMPFILE		+=	"test|||file"
TMPFILE		+=	tmp
TMPFILE		+=	z
TMPFILE		+=	.lol
TMPFILE		+=	'test\ file'

CFLAGS		=	-Werror -Wextra
CFLAGS		+=	-I../include/
CFLAGS		+= 	--coverage -lcriterion -lgcov

LDFLAGS 	=	-L../lib/ -lmy

clean:
	@rm -rf *.gcda
	@rm -rf *.gcno
	@echo -e "\033[1;31mUnit tests deleted.\033[0m"

fclean:	clean
	@rm -rf $(NAME)
	@rm -rf ../$(NAME)

libs:
	@make --no-print-directory -C ../lib/my/
	@echo -e "\033[1;33mLibs made.\033[0m"

$(NAME):	fclean libs
	@$(CC) -o $(NAME) $(TESTS) $(SRCS) $(CFLAGS) $(LDFLAGS)
	@cp $(NAME) ../
	@echo -e "\033[1;33mUnit tests created.\033[0m"

tests_run: $(NAME)
	@echo -e "\033[1;32mExecuting unit tests and gcovr...\033[0m"
	@./$(NAME) || true
	@rm -rf $(TMPFILE)
