#!/bin/python3
import os
from sys import argv

if __name__ == "__main__":
    if len(argv) == 2:
        file_content = argv[1].split(",")
        for file in file_content:
            if not os.path.exists(file):
                print("::error file=" + file + "::File not found")
                exit(1)
            if not os.access(file, os.X_OK):
                print("::error file=" + file + "::File is not executable")
                exit(1)
        print("::notice title=Program compilation::All programs was compiled successfully")
        exit(0)
    else:
        print("::notice title=Program compilation::All programs was compiled successfully")
        exit(0)
